/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DICCIONARIO_H_RPCGEN
#define _DICCIONARIO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	int nDict;
	char *text;
	int sizeT;
};
typedef struct data data;

#define DICCIONARIO 0x123456AB
#define DICCIONARIO_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define init 1
extern  int * init_1(int *, CLIENT *);
extern  int * init_1_svc(int *, struct svc_req *);
#define addword 2
extern  int * addword_1(data *, CLIENT *);
extern  int * addword_1_svc(data *, struct svc_req *);
#define verify 3
extern  int * verify_1(data *, CLIENT *);
extern  int * verify_1_svc(data *, struct svc_req *);
#define suggestword 4
extern  char ** suggestword_1(data *, CLIENT *);
extern  char ** suggestword_1_svc(data *, struct svc_req *);
#define readtext 5
extern  char ** readtext_1(data *, CLIENT *);
extern  char ** readtext_1_svc(data *, struct svc_req *);
#define show 6
extern  char ** show_1(data *, CLIENT *);
extern  char ** show_1_svc(data *, struct svc_req *);
extern int diccionario_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define init 1
extern  int * init_1();
extern  int * init_1_svc();
#define addword 2
extern  int * addword_1();
extern  int * addword_1_svc();
#define verify 3
extern  int * verify_1();
extern  int * verify_1_svc();
#define suggestword 4
extern  char ** suggestword_1();
extern  char ** suggestword_1_svc();
#define readtext 5
extern  char ** readtext_1();
extern  char ** readtext_1_svc();
#define show 6
extern  char ** show_1();
extern  char ** show_1_svc();
extern int diccionario_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);

#else /* K&R C */
extern bool_t xdr_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DICCIONARIO_H_RPCGEN */
