/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "diccionario.h"

bool_t
xdr_data (XDR *xdrs, data *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->nDict))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->text, 200))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->sizeT))
		 return FALSE;
	return TRUE;
}
